# docker-compose.yml
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourDB
      - CLOUDINARY_API_KEY=349226115814133
      - CLOUDINARY_API_SECRET=9xGGCtd-2gKMmzjpKsooqDJzOhI
      - CLOUDINARY_CLOUD_NAME=dngpv3agg
      - CLOUDINARY_URL=cloudinary://349226115814133:9xGGCtd-2gKMmzjpKsooqDJzOhI@dngpv3agg
      - JWT_SECRET=hommade-goodness
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: